import { supabase } from '@/lib/supabaseClient';
import { EventFormData } from '@/types/event';

/**
 * Centralized access to the `public.events` table.
 * Keep column names here so UI files don't need to know DB structure.
 */
const EVENTS_TABLE = 'events' as const;

export type EventRowForHistory = {
    id: string;
    title: string | null;
    category: string | null;
    date: string | null;
    location: string | null;
    maxparticipants: number | null;
    minparticipants?: number | null;
    currentparticipants?: number | null;
    fee: number | null;
    languages: any;
    tags: any;
    images: any;
    description: string | null;
    inoutdoor: 'in' | 'out' | null;
};

export async function fetchRecentEvents(limit = 20): Promise<EventRowForHistory[]> {
    const { data, error } = await supabase
        .schema('public')
        .from(EVENTS_TABLE)
        .select('id,title,category,date,location,maxparticipants,minparticipants,currentparticipants,fee,languages,tags,images,description,inoutdoor')
        // If your table doesn't have created_at, change this to 'id' or 'date'.
        .order('created_at', { ascending: false })
        .limit(limit);

    if (error) {
        throw error;
    }

    return (data || []) as unknown as EventRowForHistory[];
}

function buildDateTimeText(date: string, time?: string) {
    return date ? `${date}${time ? ` ${time}` : ''}` : '';
}

/**
 * Insert a new event (id is generated by client: Date.now()).
 */
export async function createEvent(params: {
    form: EventFormData;
    time: string;
    selectedLanguages: string[];
    tags: string[];
    images: string[];
}): Promise<{ id: string }> {
    const { form, time, selectedLanguages, tags, images } = params;

    const id = String(Date.now());
    const dateTimeText = buildDateTimeText(form.date, time);

    const dayOfWeek = form.dayOfWeek ?? 'mon';
    const period = form.period ?? 1;

    const { error } = await supabase
        .schema('public')
        .from(EVENTS_TABLE)
        .insert({
            id,
            title: form.title,
            description: form.description,
            category: form.category,
            date: dateTimeText,
            dayofweek: dayOfWeek,
            period,
            location: form.location,
            minparticipants: form.minParticipants ?? 2,
            maxparticipants: form.maxParticipants,
            currentparticipants: 0,
            fee: form.fee ?? 0,
            languages: selectedLanguages,
            organizer_id: null,
            organizer_name: '未設定',
            organizer_avatar: '',
            tags,
            images,
            inoutdoor: form.inoutdoor ?? 'in',
        });

    if (error) {
        throw error;
    }

    return { id };
}

/**
 * Update an event by id.
 */
export async function updateEvent(params: {
    id: string;
    form: EventFormData;
    time: string;
    selectedLanguages: string[];
    tags: string[];
    images: string[];
}): Promise<void> {
    const { id, form, time, selectedLanguages, tags, images } = params;

    const dateTimeText = buildDateTimeText(form.date, time);

    const dayOfWeek = form.dayOfWeek ?? 'mon';
    const period = form.period ?? 1;

    const { error } = await supabase
        .schema('public')
        .from(EVENTS_TABLE)
        .update({
            title: form.title,
            description: form.description,
            category: form.category,
            date: dateTimeText,
            dayofweek: dayOfWeek,
            period,
            location: form.location,
            minparticipants: form.minParticipants ?? 2,
            maxparticipants: form.maxParticipants,
            fee: form.fee ?? 0,
            languages: selectedLanguages,
            tags,
            images,
            inoutdoor: form.inoutdoor ?? 'in',
        })
        .eq('id', id);

    if (error) {
        throw error;
    }
}
